# Generated by Django 5.2.8 on 2025-12-01 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sell_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='products',
            field=models.ManyToManyField(related_name='sells_items', through='api.SellItem', to='api.product'),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='api.sell'),
        ),
    ]
