# Generated by Django 5.2.8 on 2025-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sell_products_alter_sellitem_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='status',
        ),
        migrations.AddField(
            model_name='sell',
            name='type_pay',
            field=models.CharField(choices=[('Tarjeta credito', 'Credito'), ('Tarjeta debito', 'Debito'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=15),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
