# Generated by Django 5.2.8 on 2025-12-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'brand', 'model')},
        ),
    ]
