# Generated by Django 5.2.8 on 2025-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
