# Generated by Django 5.2.8 on 2025-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_name_alter_sell_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='products',
            field=models.ManyToManyField(related_name='sell_items', through='api.SellItem', to='api.product'),
        ),
    ]
